# Generated by Django 4.2.2 on 2023-07-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_service', models.PositiveIntegerField()),
                ('number_of_region', models.PositiveIntegerField()),
                ('number_of_availability_zone', models.PositiveIntegerField()),
            ],
        ),
    ]
